### ISSUE TITLE
Crash after long sleep

### ISSUE THREAD

**Issue by melaww** [emoacht/Wifinian#12]
Program often disappears from systray or crashes after waking up machine after standby/sleep overnight.
[exception.log](https://github.com/emoacht/Wifinian/files/6227723/exception.log)
Can provide details on request.

**Comment by emoacht** [comment]
Thank you for the log.
It helped me to identify where the exception happens. A Win32 API seems to return unexpected value.
Then, what exactly happens when this app "disappears from systray"? Does it crash or silently closed?

**Comment by melaww** [comment]
Sometimes crash with exception, sometimes it's just silently closed. That
means, if I go with the mouse over the systray icon, it disappears.

I will pay more attention to the exact behaviour.

emoacht ***@***.***> schrieb am Di., 30. März 2021, 12:18:

**Comment by emoacht** [comment]
I see. An exception case is easy but silent death case is hard if it is caused by different reason. I will fix the exception case first. Then we will wait and see.

**Comment by emoacht** [comment]
Released Ver 2.8

**Comment by melaww** [comment]
Oh sweet, I will install it right away&update the issue with the results.

BR,
Stefan

Am Di., 30. März 2021 um 12:53 Uhr schrieb emoacht ***@***.***

**Comment by emoacht** [comment]
I made a mistake in Ver 2.8.0.
Use Ver 2.8.1 instead.

**Comment by melaww** [comment]
Looking good so far. Let me observe the behaviour over the next couple of days, then I will close the issue.

**Comment by melaww** [comment]
Working flawless. Thanks again.
