### ISSUE TITLE
Executables release

### ISSUE THREAD

**Issue by CP1832** [emoacht/Wifinian#13]
Hi emoacht, what's up? Sorry to bother but I was wondering if it was possible for a executables release for Wifinian 2.8.0, in the same  way as for Wifinian 2.6.0.

Thanks in advance.

**Comment by emoacht** [comment]
As an attempt to streamline release process, I am going to release installer only for the time being.
Please refer [Install/Uninstall](https://github.com/emoacht/Wifinian#installuninstall) section to extract executable files from installer file. It's easy.

**Comment by CP1832** [comment]
Thanks emoacht
