### ISSUE TITLE
Auto connect on startup

### ISSUE THREAD

**Issue by CP1832** [emoacht/Wifinian#5]
Hi emoacht:

I'm bothering you because each time I'm launching Wifinian for some reason, I have to manually check the Rush and Engage buttons. Is there any way to have any (or both) of these options checked automatically when starting Wifinian?

Thanks in advance.

**Comment by emoacht** [comment]
Unfortunately there is no such settings to start with Rush function on and nor plan to add such option. I believe that Rush function should not be used so often because scanning for nearby wireless networks in short intervals causes a burden to those network access points.
