### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [emoacht/Wifinian#9]
It is sad that the application is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, or any other service. It is completely free for open source projects.)

Here are examples of successful implementation:
https://github.com/xanderfrangos/twinkle-tray
https://hosted.weblate.org/projects/twinkle-tray/

https://github.com/Belphemur/SoundSwitch
https://hosted.weblate.org/projects/soundswitch
...

**Comment by bovirus** [comment]
@emoacht 

I can help to translate into italian.
What kind of language files are these

https://github.com/emoacht/Wifinian/tree/master/Source/Wifinian/Resources

**Comment by emoacht** [comment]
@KovalevArtem Thanks for your suggestion.
I could not figure out the least onerous work flow at that time.

@bovirus Thanks for your interest.
I reconfigured language contents. See the English (en) language file in develp branch. It is a plain text file containing key and value pairs delimited by '='.
https://github.com/emoacht/Wifinian/blob/develop/Source/Wifinian/Resources/language.en.txt

Copy this "language.en.txt" and rename it to "language.it.txt" as it is Italian culture. Then edit the values that you wish to translate. You can test the created file by placing it in the folder where this app's executable files exist.
